import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import "@stream-io/video-react-sdk/dist/css/styles.css";
import './globals.css';
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs';
import ConvexClientProvider from '@/components/providers/ConvexClientProvider';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import Navbar from '@/components/shared/Navbar';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ConvexClientProvider>
        <html lang='en'>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ThemeProvider
              attribute='class'
              defaultTheme='system'
              enableSystem
              disableTransitionOnChange
            >
              <SignedIn>
                <div className='min-h-screen'>
                  <Navbar />
                  <main> {children}</main>
                </div>
              </SignedIn>

              <SignedOut>
                <RedirectToSignIn />
              </SignedOut>
              <Toaster />
            </ThemeProvider>
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
